CREATE TABLE [dbo].[tblLabs] (
    [LabId]                         INT            IDENTITY (1, 1) NOT NULL,
    [LabKey]                        NVARCHAR (MAX) NULL,
    [LaboratoryName]                NVARCHAR (MAX) NULL,
    [DisplayName]                   NVARCHAR (MAX) NULL,
    [Address1]                      NVARCHAR (MAX) NULL,
    [Address2]                      NVARCHAR (MAX) NULL,
    [City]                          NVARCHAR (MAX) NULL,
    [State]                         NVARCHAR (MAX) NULL,
    [ZipCode]                       NVARCHAR (MAX) NULL,
    [Description]                   NVARCHAR (MAX) NULL,
    [MobileNumber]                  NVARCHAR (100) NULL,
    [PhoneNumber]                   NVARCHAR (MAX) NULL,
    [FaxNumber]                     NVARCHAR (MAX) NULL,
    [CLIANo]                        NVARCHAR (MAX) NULL,
    [Email]                         NVARCHAR (MAX) NULL,
    [PortalLogo]                    NVARCHAR (MAX) NULL,
    [ResultsHeader]                 NVARCHAR (MAX) NULL,
    [RequisitionHeader]             NVARCHAR (MAX) NULL,
    [MarketingLogo]                 NVARCHAR (MAX) NULL,
    [PatientPortalURL]              NVARCHAR (MAX) NULL,
    [CreateDate]                    DATETIME2 (7)  CONSTRAINT [DF_tblLabs_CreateDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                      BIT            CONSTRAINT [DF_tblLabs_IsActive] DEFAULT ((1)) NOT NULL,
    [CriticalContactName]           NVARCHAR (MAX) NULL,
    [CriticalContactPhone]          NVARCHAR (MAX) NULL,
    [IsDeleted]                     BIT            CONSTRAINT [DF__tblLabs__IsDelet__37703C52] DEFAULT ((0)) NOT NULL,
    [IsReferenceLab]                BIT            CONSTRAINT [DF__tblLabs__IsRefer__395884C4] DEFAULT ((0)) NOT NULL,
    [LabUrl]                        NVARCHAR (200) NULL,
    [CopyFromLab]                   INT            NULL,
    [DBName]                        NVARCHAR (300) NULL,
    [CreatedBy]                     NVARCHAR (200) NULL,
    [UpdatedBy]                     NVARCHAR (200) NULL,
    [UpdatedDate]                   DATETIME2 (7)  NULL,
    [isDeleteAssignedReferenceLabs] BIT            NULL,
    [isDeletePatients]              BIT            NULL,
    [isDeleteUsers]                 BIT            NULL,
    [isDeleteAssignedInsurances]    BIT            NULL,
    [isDeleteFacilities]            BIT            NULL,
    [isDeleteICD10Assignment]       BIT            NULL,
    [isDeleteInsuranceAssignment]   BIT            NULL,
    [Status]                        INT            NULL,
    [Enter3DigitsProgram]           NCHAR (3)      NULL,
    [Enter3DigitsLabCode]           NCHAR (3)      NULL,
    [LabType]                       SMALLINT       NULL,
    [IsEnableReferenceId]           BIT            NULL,
    CONSTRAINT [PK__Labs__EDBD68DA6B8ACC1A] PRIMARY KEY CLUSTERED ([LabId] ASC)
);

