CREATE TABLE [dbo].[tblUser] (
    [ID]                NVARCHAR (200) NOT NULL,
    [UserAccountType]   INT            NULL,
    [Username]          NVARCHAR (200) NULL,
    [PasswordHash]      NVARCHAR (MAX) NULL,
    [Email]             NVARCHAR (200) NULL,
    [SecurityQuestion1] NVARCHAR (MAX) NULL,
    [SecurityQuestion2] NVARCHAR (MAX) NULL,
    [SecurityAnswer1]   NVARCHAR (MAX) NULL,
    [SecurityAnswer2]   NVARCHAR (MAX) NULL,
    [IsActive]          BIT            CONSTRAINT [DF_tblUser_IsActive] DEFAULT ((1)) NOT NULL,
    [CreateDate]        DATETIME2 (7)  CONSTRAINT [DF__tblUser__CreateD__2C3393D0] DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]         NVARCHAR (MAX) NULL,
    [UpdatedDate]       DATETIME2 (7)  NULL,
    [FirstName]         NVARCHAR (200) NULL,
    [MiddleName]        NVARCHAR (200) NULL,
    [LastName]          NVARCHAR (200) NULL,
    [Gender]            NVARCHAR (50)  NULL,
    [IsDeleted]         BIT            CONSTRAINT [DF__tblUser__IsDelet__2D27B809] DEFAULT ((0)) NOT NULL,
    [ProfileImage]      NVARCHAR (MAX) NULL,
    [MobileNumber]      NVARCHAR (200) NULL,
    [PhoneNumber]       NVARCHAR (200) NULL,
    [UserType]          INT            CONSTRAINT [DF_tblUser_UserType] DEFAULT ((0)) NOT NULL,
    [Address1]          NVARCHAR (200) NULL,
    [Address2]          NVARCHAR (200) NULL,
    [ZipCode]           NVARCHAR (200) NULL,
    [State]             NVARCHAR (200) NULL,
    [City]              NVARCHAR (200) NULL,
    [IsDirector]        BIT            CONSTRAINT [DF__tblUser__IsDirec__47A6A41B] DEFAULT ((0)) NOT NULL,
    [DateOfBirth]       DATE           NULL,
    [UserTitle]         NVARCHAR (MAX) NULL,
    [AdminType]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK__tblUser__3214EC07A7CB5367] PRIMARY KEY CLUSTERED ([ID] ASC)
);

