CREATE TABLE [dbo].[tblCompendiumTestConfigurations] (
    [ID]                        INT            IDENTITY (1, 1) NOT NULL,
    [TestID]                    INT            NULL,
    [GroupTestID]               INT            NULL,
    [TestDisplayName]           NVARCHAR (MAX) NULL,
    [ReferenceLabID]            INT            NULL,
    [ExernalMappingKey]         NVARCHAR (MAX) NULL,
    [TestCode]                  NVARCHAR (MAX) NULL,
    [OrderCode]                 NVARCHAR (MAX) NULL,
    [ResultCode]                NVARCHAR (MAX) NULL,
    [ReqTypeID]                 INT            NULL,
    [Department]                NVARCHAR (MAX) NULL,
    [Unit]                      NVARCHAR (MAX) NULL,
    [SpecimenTypeID]            INT            NULL,
    [ResultType]                NVARCHAR (MAX) NULL,
    [InstrumentName]            NVARCHAR (MAX) NULL,
    [InstrumentResultingMethod] NVARCHAR (MAX) NULL,
    [CalcuationFormulaID]       INT            NULL,
    [OrderMethodType]           NVARCHAR (MAX) NULL,
    [OrderMethodName]           NVARCHAR (MAX) NULL,
    [CPTCode]                   NVARCHAR (MAX) NULL,
    [IsControl]                 BIT            CONSTRAINT [DF_tblCompendiumTestConfigurations_IsControl] DEFAULT ((1)) NULL,
    [SortOrder]                 INT            NULL,
    [IsActive]                  BIT            CONSTRAINT [DF_tblCompendiumTestConfigurations_isActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                 BIT            CONSTRAINT [DF_tblCompendiumTestConfigurations_IsDeleted] DEFAULT ((0)) NULL,
    [CreatedBy]                 NVARCHAR (MAX) NOT NULL,
    [CreatedDate]               DATETIME2 (7)  NOT NULL,
    [UpdatedBy]                 NVARCHAR (MAX) NULL,
    [UpdatedDate]               DATETIME2 (7)  NULL,
    [DeletedBy]                 NVARCHAR (MAX) NULL,
    [DeletedDate]               DATETIME2 (7)  NULL,
    CONSTRAINT [PK_tblCompendiumTestConfigurations] PRIMARY KEY CLUSTERED ([ID] ASC)
);

