CREATE TABLE [dbo].[tblFacility] (
    [FacilityId]            INT            IDENTITY (1, 1) NOT NULL,
    [FacilityName]          NVARCHAR (MAX) NULL,
    [Address]               NVARCHAR (MAX) NULL,
    [Address2]              NVARCHAR (MAX) NULL,
    [State]                 NVARCHAR (MAX) NOT NULL,
    [City]                  NVARCHAR (MAX) NULL,
    [ZipCode]               NVARCHAR (MAX) NULL,
    [County]                NVARCHAR (MAX) NULL,
    [FacilityPhone]         NVARCHAR (MAX) NULL,
    [FacilityFax]           NVARCHAR (MAX) NULL,
    [ContactFirstName]      NVARCHAR (MAX) NULL,
    [ContactLastName]       NVARCHAR (MAX) NULL,
    [ContactPrimaryEmail]   NVARCHAR (MAX) NULL,
    [ContactPhone]          NVARCHAR (MAX) NULL,
    [CriticalFirstName]     NVARCHAR (MAX) NULL,
    [CriticalLastName]      NVARCHAR (MAX) NULL,
    [CriticalContactEmail]  NVARCHAR (MAX) NULL,
    [CriticalPhone]         NVARCHAR (MAX) NULL,
    [Status]                NVARCHAR (MAX) NULL,
    [IsFaxEnabled]          BIT            NULL,
    [Notes]                 NVARCHAR (MAX) NULL,
    [LocationCode]          NVARCHAR (MAX) NULL,
    [OrganizationCode]      NVARCHAR (MAX) NULL,
    [IsSuspended]           BIT            CONSTRAINT [DF_tblFacility_IsSuspended] DEFAULT ((0)) NULL,
    [IsDeleted]             BIT            CONSTRAINT [DF__tblFacili__IsDel__01142BA1] DEFAULT ((0)) NULL,
    [CreatedTime]           DATETIME2 (7)  NULL,
    [CreatedBy]             NVARCHAR (MAX) NULL,
    [UpdateTime]            DATETIME2 (7)  NULL,
    [UpdatedBy]             NVARCHAR (MAX) NULL,
    [DeleteDate]            DATETIME2 (7)  NULL,
    [DeletedByUserId]       NVARCHAR (300) NULL,
    [AccountActivationType] INT            NULL,
    [FacilityWebsite]       NVARCHAR (MAX) NULL,
    [IsApproved]            BIT            NULL,
    CONSTRAINT [PK__tblFacil__5FB08A74FB2CAFF1] PRIMARY KEY CLUSTERED ([FacilityId] ASC)
);

