CREATE TABLE [dbo].[tblIDLISResultInformation] (
    [ID]                   INT             IDENTITY (1, 1) NOT NULL,
    [FileID]               INT             NULL,
    [FileName]             NVARCHAR (MAX)  NULL,
    [FileType]             NVARCHAR (MAX)  NULL,
    [LabID]                INT             NOT NULL,
    [RequisitionTypeID]    INT             NOT NULL,
    [AccessionNumber]      NVARCHAR (MAX)  NULL,
    [PanedID]              INT             NULL,
    [PanelName]            NVARCHAR (MAX)  NULL,
    [TestID]               INT             NULL,
    [TestName]             NVARCHAR (MAX)  NULL,
    [Result]               NVARCHAR (MAX)  NULL,
    [CombinedResult]       NVARCHAR (MAX)  NULL,
    [CtMeans]              NVARCHAR (MAX)  NULL,
    [AMPScore]             DECIMAL (18, 6) NULL,
    [CRTSD]                DECIMAL (18, 6) NULL,
    [CqConf]               DECIMAL (18, 6) NULL,
    [Qualitative]          NVARCHAR (MAX)  NULL,
    [IsReRun]              BIT             NULL,
    [CtmeansRerun]         NVARCHAR (MAX)  NULL,
    [AntibioticClass]      NVARCHAR (50)   NULL,
    [EstMicrobialLoad]     NVARCHAR (MAX)  NULL,
    [PharmdInterpretation] NVARCHAR (50)   NULL,
    [OrganismType]         NVARCHAR (MAX)  NULL,
    [DisplayOrder]         INT             NULL,
    [IsControl]            BIT             NULL,
    [CorrectedValue]       NVARCHAR (MAX)  NULL,
    [RequisitionID]        INT             NULL,
    [RecordID]             INT             NULL,
    [CreatedBy]            NVARCHAR (MAX)  NULL,
    [CreatedDate]          DATETIME2 (7)   NULL,
    [UpdatedBy]            NVARCHAR (MAX)  NULL,
    [UpdatedDate]          DATETIME2 (7)   NULL,
    CONSTRAINT [PK_tblLISResultData] PRIMARY KEY CLUSTERED ([ID] ASC)
);

