CREATE TABLE [dbo].[tblIDLISRawResultData] (
    [RawDataID]            INT            NOT NULL,
    [UploadFileID]         INT            NULL,
    [Well]                 NVARCHAR (MAX) NULL,
    [WellPosition]         NVARCHAR (MAX) NULL,
    [Omit]                 NVARCHAR (MAX) NULL,
    [SampleName]           NVARCHAR (MAX) NULL,
    [TargetName]           NVARCHAR (MAX) NULL,
    [Task]                 NVARCHAR (MAX) NULL,
    [Reporter]             NVARCHAR (MAX) NULL,
    [Quencher]             NVARCHAR (MAX) NULL,
    [CT]                   NVARCHAR (MAX) NULL,
    [CtMean]               NVARCHAR (MAX) NULL,
    [CtSD]                 NVARCHAR (MAX) NULL,
    [Quantity]             NVARCHAR (MAX) NULL,
    [QuantityMean]         NVARCHAR (MAX) NULL,
    [QuantitySD]           NVARCHAR (MAX) NULL,
    [AutomaticCtThreshold] NVARCHAR (MAX) NULL,
    [CtThreshold]          NVARCHAR (MAX) NULL,
    [AutomaticBaseline]    NVARCHAR (MAX) NULL,
    [BaselineStart]        NVARCHAR (MAX) NULL,
    [BaselineEnd]          NVARCHAR (MAX) NULL,
    [Comments]             NVARCHAR (MAX) NULL,
    [YIntercept]           NVARCHAR (MAX) NULL,
    [RSuperscript2]        NVARCHAR (MAX) NULL,
    [Slope]                NVARCHAR (MAX) NULL,
    [AmpScore]             NVARCHAR (MAX) NULL,
    [CqConf]               NVARCHAR (MAX) NULL,
    [AmpStatus]            NVARCHAR (MAX) NULL,
    [OffScale]             NVARCHAR (MAX) NULL,
    [ExpFail]              NVARCHAR (MAX) NULL,
    [Noise]                NVARCHAR (MAX) NULL,
    [Spike]                NVARCHAR (MAX) NULL,
    [IsProcessed]          BIT            NULL,
    [ExceptionMessage]     NVARCHAR (MAX) NULL,
    [CreatedBy]            NVARCHAR (MAX) NULL,
    [CreatedDate]          DATETIME2 (7)  NULL,
    CONSTRAINT [PK_tblLISRawResultData] PRIMARY KEY CLUSTERED ([RawDataID] ASC)
);

