CREATE TABLE [dbo].[tblLabSectionControls] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [LabID]                INT            NULL,
    [PageID]               INT            NULL,
    [SectionID]            INT            NULL,
    [ControlID]            INT            NULL,
    [ControlKey]           NVARCHAR (MAX) NOT NULL,
    [ControlName]          NVARCHAR (MAX) NOT NULL,
    [TypeOfControl]        NVARCHAR (MAX) NOT NULL,
    [DefaultValue]         NVARCHAR (MAX) NULL,
    [Options]              NVARCHAR (MAX) NULL,
    [SortOrder]            INT            NOT NULL,
    [FormatMask]           NVARCHAR (MAX) NULL,
    [ColumnValidation]     NVARCHAR (MAX) NULL,
    [IsVisible]            BIT            CONSTRAINT [DF_tblSectionControl_isActive] DEFAULT ((1)) NOT NULL,
    [isSystemRequired]     BIT            CONSTRAINT [DF_tblSectionControl_isSystemRequired] DEFAULT ((0)) NOT NULL,
    [CreatedBy]            NVARCHAR (MAX) NOT NULL,
    [CreatedDate]          DATETIME2 (7)  NOT NULL,
    [UpdatedBy]            NVARCHAR (MAX) NULL,
    [UpdatedDate]          DATETIME2 (7)  NULL,
    [TypeOfSection]        NVARCHAR (MAX) NULL,
    [CssStyle]             NVARCHAR (MAX) NULL,
    [DisplayType]          NVARCHAR (MAX) NULL,
    [ControlValue]         NVARCHAR (MAX) NULL,
    [ControlData]          NVARCHAR (MAX) NULL,
    [OrderViewSortOrder]   INT            NULL,
    [OrderViewDisplayType] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_tblLabSectionControls] PRIMARY KEY CLUSTERED ([ID] ASC)
);

