CREATE TABLE [dbo].[ToxPanelTest] (
    [Id]                     INT            NOT NULL,
    [LabId]                  INT            NULL,
    [PanelId]                INT            NULL,
    [PanelGroupId]           INT            NULL,
    [PanelGroupCode]         VARCHAR (MAX)  NULL,
    [LabReferenceCode]       VARCHAR (MAX)  NULL,
    [SubPanel]               VARCHAR (MAX)  NULL,
    [CommonTestName]         VARCHAR (MAX)  NULL,
    [SystemTestName]         VARCHAR (MAX)  NULL,
    [DrugClassName]          VARCHAR (MAX)  NULL,
    [LabTestName]            VARCHAR (MAX)  NULL,
    [IntegrationType]        VARCHAR (MAX)  NULL,
    [PanelCode]              VARCHAR (MAX)  NULL,
    [PanelType]              VARCHAR (MAX)  NULL,
    [RequisitionType]        VARCHAR (MAX)  NULL,
    [SpecimentType]          VARCHAR (MAX)  NULL,
    [CuttOffValues]          VARCHAR (MAX)  NULL,
    [UpperLimit]             VARCHAR (MAX)  NULL,
    [Units]                  VARCHAR (MAX)  NULL,
    [LOINC]                  VARCHAR (MAX)  NULL,
    [CPTCodes]               VARCHAR (MAX)  NULL,
    [AssociatedMedications]  VARCHAR (MAX)  NULL,
    [IsActive]               BIT            NULL,
    [CreatedBy]              VARCHAR (MAX)  NULL,
    [CreatedDate]            DATETIME       NULL,
    [UpdatedBy]              VARCHAR (MAX)  NULL,
    [UpdatedDate]            DATETIME       NULL,
    [IsSpecimenValidatyTest] BIT            NULL,
    [EdenOrderTestCode]      VARCHAR (250)  NULL,
    [EdenResultTestCode]     VARCHAR (250)  NULL,
    [ReceivedBy]             VARCHAR (100)  NULL,
    [PerformingLab]          VARCHAR (MAX)  NULL,
    [ReqID]                  VARCHAR (MAX)  NULL,
    [TestAssignmentId]       INT            NULL,
    [DrugClass]              NVARCHAR (MAX) NULL
);

